components:
  installer_builder:
    id: pyinstaller_builder
    hint_path: infrastructure
    singleton: true

  release_publisher:
    id: github_release
    hint_path: infrastructure
    singleton: true